// Pokemon Actions
export const ADD_POKEMON = "ADD_POKEMON";
// Comment actions
export const GET_COMMENT = "GET_COMMENT";
export const ADD_COMMENT = "ADD_COMMENT";
export const DEL_COMMENT = "DEL_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const SORT_COMMENT = "SORT_COMMENT";
export const LIKE_COMMENT = "LIKE_COMMENT";
export const LIKE_POKE = "LIKE_POKE";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const VALID_OTP = "VALID_OPT";
export const CLEAR_FORGOT_PASSWORD = "CLEAR_FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const CLEAR_RESET_PASSWORD = "CLEAR_RESET_PASSWORD";
export const VALID_RESET_TOKEN = "VALID_RESET_TOKEN";
export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE';
export const VERIFY_ACCOUNT = 'VERIFY_ACCOUNT';
export const REQUEST_NEW_VERIFICATION_LINK = 'REQUEST_NEW_VERIFICATION_LINK';
export const FAVORITE_ITEM_CLICKED = 'FAVORITE_ITEM_CLCIKED';
export const FAVORITE_ITEM_CLICKED_CLEAR= 'FAVORITE_ITEM_CLICKED_CLEAR';
export const GET_USER_COMMENTS = 'GET_USER_COMMENTS';
export const UPLOAD_PIC = 'UPLOAD_PIC';
export const GET_USER_DATA = 'GET_USER_DATA';
